#!/bin/bash

# get package location, which contains all other executables
SCRIPT_DIR="$(python3 -c \
'import pkg_resources as p
print(p.resource_filename("skim_unicode_table", ""))'\
)"

"$SCRIPT_DIR"/run-xsel.sh "$@"
