# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_install_from_wd:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
    steps:
    - name: Check out repo and submodule repos
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install our package
      run: |
        python -m pip install .
  build_wheels_x86_64:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux_2_24_x86_64
    strategy:
      fail-fast: false
      matrix:
        pyver: [39]
    steps:
    - name: cd /io
      run: cd /io
    - name: Check out repo and submodule repos
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Rust
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y
        export PATH="$HOME/.cargo/bin:$PATH"
    - name: Install dependencies
    - run: |
        export PYBIN=/opt/python/cp${{ matrix.pyver }}*/bin
        "${PYBIN}/pip" install -U setuptools wheel setuptools-rust
    - name: Build wheel
      run: |
        "${PYBIN}/python" setup.py bdist_wheel
    - name: Audit wheel
      run: |
        for whl in dist/*.whl; do
            auditwheel repair "$whl" -w dist/
        done
